function saveTrajectory(txu,fname,colname)
% Wrapper function for writematrix 
arguments
    txu (:,7) {mustBeNumeric}
    fname (1,1) string = "untitled.csv";
    colname (1,7) string = [...
                            "Time, ms",...
                            "Yaw Angle, rad",...
                            "Hidden State 1",...
                            "Hidden State 2",...
                            "Hidden State 3",...
                            "Hidden State 4",...
                            "Feed-Forward Asymmetry, rad"...
                            ];
end

writematrix(...
    [...
        colname;
        string(txu)...
    ],...
    fname);
end